FROM registry.gitlab.com/raspi-alpine/builder/3-19:latest

RUN apk add --no-cache build-base git bash automake autoconf libtool linux-headers libpcap net-snmp-libs net-snmp-agent-libs bsd-compat-headers
