FROM registry.gitlab.com/raspi-alpine/builder/master:latest

RUN apk add --no-cache build-base alpine-sdk git bash automake autoconf libtool linux-headers libpcap net-snmp-libs net-snmp-agent-libs bsd-compat-headers musl-nscd-dev pps-tools pps-tools-dev
